### ISSUE TITLE
EIP-3651: Warm COINBASE

### ISSUE THREAD

**Issue by andreiburdusa** [NethermindEth/EVMYulLean#7]
https://eips.ethereum.org/EIPS/eip-3651

Starts the `COINBASE` address warm.

**Comment by SimonVervisch** [comment]
Hi, 
Apparently, the ORIGIN address and the tx.to address  (which you define as the recipient) should be loaded. I don't know if this occurs?

**Comment by andreiburdusa** [comment]
It looks like the Yellow Paper version we used to model transactions in #23 already specified this improvement.
![image](https://github.com/user-attachments/assets/6ac84c8c-66aa-464a-bd3d-b1fa9e4a62c2)
- _Aa*_ is the set of accessed account addresses of the substate given as argument to `Lambda` or `Θ`.
- _Hc_ is the result of `COINBASE`.
- _S(T)_ is the sender of the transaction, aka `tx.sender`, `Io` or the result of `ORIGIN`.
- _Tt_ is the message call's recipient, `to`.

If it is a contract creation transaction then the address being created is added by the contract creation function `Lambda`.
